export * from './AboutUsPage'
export * from './AdminEditUserPage'
export * from './AdminUserPage'
export * from './CreateHospitalPage'
export * from './HomePage'
export * from './LoadingPage'
export * from './MapPage'
export * from './PatientsHospitalPage'
